-- MySQL Script generated by MySQL Workbench
-- dom 11 ago 2019 20:08:26 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema RecursosEmpresa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RecursosEmpresa` ;

-- -----------------------------------------------------
-- Schema RecursosEmpresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RecursosEmpresa` DEFAULT CHARACTER SET utf8 ;
USE `RecursosEmpresa` ;

-- -----------------------------------------------------
-- Table `RecursosEmpresa`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RecursosEmpresa`.`empleado` ;

CREATE TABLE IF NOT EXISTS `RecursosEmpresa`.`empleado` (
  `idempleado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `designacion` VARCHAR(45) NULL DEFAULT NULL,
  `sueldo` DECIMAL(9,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idempleado_UNIQUE` ON `RecursosEmpresa`.`empleado` (`idempleado` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
